### ISSUE TITLE
Filter SamplingFeature by Type=Site in the list display.

### ISSUE THREAD

**Issue by denvaar** [ODM2/ODM2StreamingDataLoader#13]

**Comment by kwuz** [comment]
Currently, the 'create sampling feature' panel is type locked to only be able to add Site type sampling features. Is this what is wanted? Will any sampling features that aren't site type find their way on the list in the first place?

if so,

Is there a db/testfile I can use to test this issue that has sampling features that are not Site type? all of mine only contain site types.

**Comment by horsburgh** [comment]
We only want data from sensors to be associated with sites. If the ODM2 database has other samplingfeatures in it that are not sites, we want them to NOT appear for selection.

**Comment by kwuz** [comment]
did some digging in the code and looks like this is already done. Not sure when or by whom this was completed.
