### ISSUE TITLE
Time Units not populated for blank database

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2StreamingDataLoader#23]
For a blank database, there are no time units populated, preventing the selection of the intended time spacing. We need to permit the user to create the units or else automatically recognize and populate with time units.

![image](https://cloud.githubusercontent.com/assets/5023186/12662228/1cf7a972-c5dc-11e5-94ac-64a52b22aa7b.png)

**Comment by kwuz** [comment]
ready for testing, branch issue_23
The default time units I added can be easily changed if need be. There are likely still other issues regarding blank databases lurking in the program. I'll do a bit of testing and open issues as I find them.

**Comment by sreeder** [comment]
We don't want to populate it with default values. We want to have a "Create New.." option always added to the end. and if it is selected it will popup the wizard that creates a new unit

**Comment by kwuz** [comment]
@sreeder how about a combobox that allows you to type your own values?
That way we could pre-populate "expected" values but still allow creation of new ones without adding another dialog?

**Comment by sreeder** [comment]
@kwuz. We actually have no idea what they want their database to contain. and this has to point to an already existing unit within the database. Their units could be entirely different. so if you did a combo box you would have to create the unit in the database when they type in the value

**Comment by kwuz** [comment]
hm, a full dialog it is then probably. Will we need any information about the unit other than the name?

**Comment by sreeder** [comment]
@kwuz 
there should already be a dialog to create the unit. we just need to pull it up.

**Comment by sreeder** [comment]
This issue has been addressed
