### ISSUE TITLE
Need to be able to create a Method

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2StreamingDataLoader#27]
When creating a new Action, the user is required to select a Method. If a database is blank, there are no Methods available for selection. We need to permit the user to create a Method or create an unknown Method.

**Comment by kwuz** [comment]
What would need to be included in a "create new method" type dialog?

**Comment by AmberSJones** [comment]
Creating a new method would need to populate the Methods table:

![image](https://cloud.githubusercontent.com/assets/5023186/18317571/d74ea3bc-74db-11e6-9590-69ffa73e28c2.png)

A user should be able to select the method type from a list, populate the method name, description, link, and select an organization from a list.

**Comment by horsburgh** [comment]
MethodDescription, MethodLink, and OrganizationID are optional attributes.

**Comment by PhilSuiter** [comment]
This looks great, and works too! Good job. 
![image](https://cloud.githubusercontent.com/assets/12566275/19937644/ae405b90-a0e7-11e6-981a-cbe8e897aecb.png)
http://giphy.com/gifs/thumbs-up-AEohJsxlO6nJK

**Comment by sreeder** [comment]
Looks good. I am closing.
