### ISSUE TITLE
Make all combo boxes on the "Add New..." forms read-only.

### ISSUE THREAD

**Issue by denvaar** [ODM2/ODM2StreamingDataLoader#3]

**Comment by denvaar** [comment]
Sampling Feature - DONE

**Comment by sreeder** [comment]
@kwuz
UnitsType in Create New Unit Form 
Method and ActionType  in Create new Action
Existing person in Create New Affiliation
Existing organization, type, and parent organization in Create New Affiliation
are not set to read only.

**Comment by kwuz** [comment]
@sreeder fixed on branch issue_3
All but the units in the result panel were already read-only on my current working branch.
also, units aren't populated. Opening an issue for that now.

**Comment by sreeder** [comment]
looks good.
