### ISSUE TITLE
Units drop down list does not have units of time for the "Intended Time Spacing" field

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODM2StreamingDataLoader#31]
In the final summary window, the units drop down list only includes units of length and not time. 

![image](https://cloud.githubusercontent.com/assets/12566275/12768312/0fd52622-c9cc-11e5-82c8-c2924cde6ef2.png)

**Comment by kwuz** [comment]
testable in the "edit_branch" branch

**Comment by PhilSuiter** [comment]
This issue has not been resolved

**Comment by farrieta9** [comment]
This issue was addressed in a previous commit. The Intended Time Spacing should now list time units (ex. min, hr, day, etc) and X, Y, and Z location now list length units (ex. cm, m, ft, etc)

**Comment by sreeder** [comment]
looks good to me. closing.
