### ISSUE TITLE
'Finish' button does not automatically close window when the location units are filled out

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODM2StreamingDataLoader#32]
When the units are chosen for the X,Y, Z location fields, the 'Finish' button does not automatically close out the summary window.  The 'Finish' button does work in the sense that it will still populate the time series result list with your previously mapped variable.  When the units are left blank and NOT filled out, everything works fine and the summary window closes upon clicking 'Finish'. 

The first image is the final summary window WITH the units filled out, which results in 'Finish' button not closing out the window.

The second image is the time series results list that displays two 'TurbBES' at the bottom of the list. The first Turb is from the 'Finish' button not closing out the window, and the second Turb is from clicking the 'Finish' button with no units filled out.  This was to show that in either case, the 'Finish' button will still populate the time series results list.

![image](https://cloud.githubusercontent.com/assets/12566275/12768360/61c04b92-c9cc-11e5-8f0b-3aba97cdc25e.png)

![image](https://cloud.githubusercontent.com/assets/12566275/12768618/1c08b146-c9ce-11e5-89c5-72715ba63821.png)

**Comment by kwuz** [comment]
Unit is being read as an int? 
![image](https://cloud.githubusercontent.com/assets/15348288/17900941/970ede34-691e-11e6-8d64-396de5a7491f.png)

**Comment by kwuz** [comment]
testable in "edit_branch" branch

**Comment by PhilSuiter** [comment]
This issue is still present, except now the Finish button does not automatically close the window even when none of the location units are filled out.

**Comment by sreeder** [comment]
it closes when I fill in the units data. Closing
