### ISSUE TITLE
'Intended Time Spacing' not updating in final summary window

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODM2StreamingDataLoader#33]
In the first 'Edit Mapping' window, I filled in the Intended Time Spacing to be 15 seconds, but in the final summary window, the Intended Time Spacing was listed as zero. 

Question: Shouldn't the time spacing in the summary window be the same time spacing input previously?  Or Is the final 'Intended Time Spacing' in the summary window supposed to be variable specific and separate from the original time spacing input?

![image](https://cloud.githubusercontent.com/assets/12566275/12800409/e8f23ab0-ca91-11e5-9ecb-a8c50ea25d53.png)

![image](https://cloud.githubusercontent.com/assets/12566275/12800453/42a6551e-ca92-11e5-803c-5f36994cd9e5.png)

**Comment by kwuz** [comment]
This was already done and never got marked ready for testing

**Comment by sreeder** [comment]
@AmberSJones  do we need this in 2 separate locations? I feel like we only need to do it in 1. and if we only do one, where would you prefer it? or was it possibly supposed to be something else?

**Comment by AmberSJones** [comment]
I think either location is fine for this. I would lean toward removing from the first screen and keeping it on the last screen. An added bonus with that, when we have a blank database, we wouldn't have to create the Units on this very first screen.

**Comment by sreeder** [comment]
As per our meeting, we will remove this from the Result Wizard page and leave it as a setting for the entire file. This will require us to get the file's intended time spacing and set it when we are creating a new Result.

**Comment by kwuz** [comment]
Ready for testing, branch issue_33

**Comment by kwuz** [comment]
Okay, ready for testing for real this time on branch issue_33b.

**Comment by sreeder** [comment]
@AmberSJones if the user changes this value, do we need to update every result in the file?

**Comment by sreeder** [comment]
this has been fully addressed
