### ISSUE TITLE
SDLLoader executable fails and gives "Fatal Error" 

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODM2StreamingDataLoader#34]
When I run the loader via SDLLoader executable, it fails to execute and I get a fatal error message that says "StreamingDataLoader returned -1". 

![image](https://cloud.githubusercontent.com/assets/12566275/13084255/f6619976-d495-11e5-9161-20879766ee27.png)

**Comment by sreeder** [comment]
I am not getting this error. Closing
