### ISSUE TITLE
The Run Data File button is left unimplemented

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODM2StreamingDataLoader#35]
After completing all the mapping edits, the "run data" button is inactivated and I can not execute a run.  The purpose of this button is to give the ability to do an "initial run" or a manual run of a configuration file. 

![image](https://cloud.githubusercontent.com/assets/12566275/13084532/f8b8f916-d496-11e5-8fb2-ead177fe0844.png)

**Comment by sreeder** [comment]
button is enabled when I have columns mapped. Closing.
