### ISSUE TITLE
Unable to edit an existing result 

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODM2StreamingDataLoader#37]
After a result has been created and committed to the database, it would be helpful to be able to edit the existing result to confirm or change the fields assigned to the result.  When I double click, or right click, on any result, nothing happens (Image 1).  There is only an option to select a result or create new result.  Maybe add an "Edit Result" Button?

![image](https://cloud.githubusercontent.com/assets/12566275/13090441/fe944036-d4b2-11e5-9945-4a585bb06b76.png)

**Comment by kwuz** [comment]
@PhilSuiter @AmberSJones What needs to be editable? Everything (going through the entire "create new" dialog) or just the items that appear on the summary page at the end? I'm trying to figure out the workflow for the user, and what will make the most sense.

**Comment by sreeder** [comment]
@kwuz 
Add a Warning message:
"you may clobber the integrity of your data, would you like to continue"
and then go back through the wizard existing with all of the metadata values preselected.

**Comment by sreeder** [comment]
@kwuz looks like this works except that hte last summary page is not populating the sampled medium and aggregation static dropdown.

**Comment by kwuz** [comment]
They're populated on my current branch, might be an old issue. Test it on branch issue_3

**Comment by sreeder** [comment]
@kwuz, are they populated with the value from the existing result?

**Comment by kwuz** [comment]
Alright, that's fixed now. Test on issue_37

**Comment by sreeder** [comment]
looks good.
