### ISSUE TITLE
Automatically Save configuration file after 'Finish' button clicked

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODM2StreamingDataLoader#39]
After the 'Finish' button is clicked, it would be helpful if the mapped out configuration file automatically saved instead of having to manually click File, Save (image).  Or have an automatic save after each variable has been assigned a result.  Just make saving more user friendly and intuitive, and create a warning that asks if you want to save before you close the file.    

![image](https://cloud.githubusercontent.com/assets/12566275/13090990/42a36114-d4b6-11e5-8363-145ebbaa1785.png)

**Comment by kwuz** [comment]
Instead of doing an autosave, I'm adding save and exit buttons at the bottom of the dialog. In addition to following convention and user expectations, it'll preserve the "save as" feature. 

A dialog will still appear alerting the user of unsaved changes if they try to exit without saving.

**Comment by PhilSuiter** [comment]
Save and Quit buttons work great!
