### ISSUE TITLE
"Run" does not find the proper path

### ISSUE THREAD

**Issue by kwuz** [ODM2/ODM2StreamingDataLoader#45]

**Comment by PhilSuiter** [comment]
When I run a completely mapped file, I click "Run" and get this error 
![image](https://cloud.githubusercontent.com/assets/12566275/17679899/dd9f1b18-62fa-11e6-85ba-ea552c3aec5c.png)

**Comment by kwuz** [comment]
okay, try pulling the latest version again from the edit_branch branch

**Comment by PhilSuiter** [comment]
Hit the run button and a 'connection was unsuccessful' error occurred. 
![image](https://cloud.githubusercontent.com/assets/12566275/19936980/19618546-a0e5-11e6-9c71-e91a12dc1942.png)

**Comment by sreeder** [comment]
this should be resolved. Closing
