### ISSUE TITLE
"New Sample Feature" is not adding new feature to the list

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODM2StreamingDataLoader#46]
After creating a new sampling feature, I click OK, but the new sampling feature does not show up on the list.
![image](https://cloud.githubusercontent.com/assets/12566275/17419479/d7e5c602-5a5a-11e6-9114-600d80b93265.png)

**Comment by sreeder** [comment]
@PhilSuiter  I believe this is associated with the fact that the ODM2 data structure itself has changed, to add a column called featuregeometrywkt.  It is an issue with the database not the program. which database are you connecting too, I will get in a fix it really quick.

**Comment by PhilSuiter** [comment]
The database is:  ODM2_LoadTest
The server is: iutahqc.uwrl.usu.edu

**Comment by sreeder** [comment]
@PhilSuiter  when you get a chance go ahead and test it again. Thanks!

**Comment by PhilSuiter** [comment]
@sreeder the issue remains.  The new sample feature still does not show up on the list.

**Comment by kwuz** [comment]
Testable in the "edit_branch"

**Comment by PhilSuiter** [comment]
This issue has been resolved
