### ISSUE TITLE
Results not loading when connected to MSSQL database

### ISSUE THREAD

**Issue by kwuz** [ODM2/ODM2StreamingDataLoader#48]
![image](https://cloud.githubusercontent.com/assets/15348288/22165893/604f23e0-df1b-11e6-85db-a3796c739c38.png)

Service connects fine to database, but does not populate time series result values from an MSSQL database on windows.

**Comment by farrieta9** [comment]
Which branch are you on? Try using the bug-fix branch. Otherwise, the data is there. Look at 
src/wizard/view/clsSeriesSelectPanel.py
Maybe change the valueGetters and get the right data.

**Comment by kwuz** [comment]
fixing the casing should have fixed this issue and be ready for testing on branch bug-fix

**Comment by sreeder** [comment]
This issue is fixed. Closing
