### ISSUE TITLE
Edit Result Wizard fails on finish

### ISSUE THREAD

**Issue by kwuz** [ODM2/ODM2StreamingDataLoader#51]
mssql server, throws detached instance error on finish button

![image](https://cloud.githubusercontent.com/assets/15348288/22355382/82c99290-e3e7-11e6-9046-e8f7e1e7785e.png)

![image](https://cloud.githubusercontent.com/assets/15348288/22355389/8e7bce00-e3e7-11e6-90a2-5fc65c9d3543.png)

**Comment by farrieta9** [comment]
Along with this error, I get 
`AttributeError: 'TimeSeriesResults' object has no attribute 'UUID'`
from the frmResultSummaryPanel.py around line 217

**Comment by kwuz** [comment]
Ready for testing, however detached instance issue is still present and makes testing difficult
