### ISSUE TITLE
DB connection fail Error Message

### ISSUE THREAD

**Issue by sreeder** [ODM2/ODM2StreamingDataLoader#54]
When you have an unsuccessful connection to a database there is no error message. We need to add a pop up message. do we want to include the error returned from the database? it will be technical so may be too confusing for a typical user

**Comment by sreeder** [comment]
Note: tested using mac and postgres

**Comment by kwuz** [comment]
There used to be an "invalid connection" dialog, I'm not sure why it's no longer appearing. 

Also, if you have a valid connection, test it, and then edit the connection so it's invalid and test the connection again, sometimes python will stop responding (?)

**Comment by sreeder** [comment]
there is a now an error message
