### ISSUE TITLE
Selecting multiple results in Edit Wizard produces errors

### ISSUE THREAD

**Issue by farrieta9** [ODM2/ODM2StreamingDataLoader#57]
When selecting multiple rows, the objects are being selected so when clicking edit none is being passed

**Comment by kwuz** [comment]
perhaps we should disable the edit button when more than one result is selected?

**Comment by sreeder** [comment]
I actually think there is a way to set the object list view to only select a single row.

**Comment by sreeder** [comment]
Only allows a single series to be selected. Closing
