### ISSUE TITLE
Affiliations Not Populated in Create New Action Form

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2StreamingDataLoader#67]
There are Affiliations in my database, but they are not populated in this form:
![image](https://cloud.githubusercontent.com/assets/5023186/24976251/f0c91908-1f85-11e7-86c4-54494fa38b08.png)

**Comment by AmberSJones** [comment]
This might help: 
![image](https://cloud.githubusercontent.com/assets/5023186/24976790/0fa9a980-1f88-11e7-82ff-33a083a00c14.png)

**Comment by sreeder** [comment]
@kwuz as you know this is still an issue

**Comment by kwuz** [comment]
so this is apparently fixed now through some black magic after merging another branch in with development....

Ready for testing on development branch? I guess?

**Comment by sreeder** [comment]
So weird. Closing
