### ISSUE TITLE
Create New Method Fails

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2StreamingDataLoader#68]
I'm trying to create a new method on the Create New Action form. I click on the + button and add the information for the Method, but nothing happens. The method should be populate in the list and should be automatically selected.

**Comment by AmberSJones** [comment]
This might help: 
![image](https://cloud.githubusercontent.com/assets/5023186/24976799/171b38d2-1f88-11e7-93fc-0538f7d6738b.png)

**Comment by kwuz** [comment]
ready for testing branch issue_68

**Comment by kwuz** [comment]
Okay, partially ready for testing. 
The create new method window no longer fails but there are other issues associated with the method panel. Should I open those as new issues?

**Comment by kwuz** [comment]
Try branch issue_68 again!
