### ISSUE TITLE
New Action Not Appearing in List

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2StreamingDataLoader#69]
I just created a new action, but it does not appear in the list of actions available for selection. It should appear and automatically be selected.

**Comment by AmberSJones** [comment]
This might help: 
![image](https://cloud.githubusercontent.com/assets/5023186/25006006/7c58d57a-2018-11e7-9a57-c371181aca32.png)

**Comment by farrieta9** [comment]
I've made a few adjustments, the error I'm running into now is that there is no self.actionLead. Somethings are not being set or maybe I don't know how to set this in the app.

**Comment by sreeder** [comment]
This issue has been addressed
