### ISSUE TITLE
"Create New Result" not functional

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2StreamingDataLoader#70]
I have tried to create a new result without success. In one case, I went through the steps and it did not appear in the list- it should appear and be pre-selected. In another case, I went through the steps and then was stuck on the summary screen with the spinning wheel (of death) before I closed it out.

**Comment by AmberSJones** [comment]
This might help: 
![image](https://cloud.githubusercontent.com/assets/5023186/25006450/25a7f024-201a-11e7-985d-8b82cb2b8082.png)

**Comment by kwuz** [comment]
issue partially fixed

**Comment by kwuz** [comment]
'no attribute 'resultID' fixed

however, new results show up blank. Treating it as a separate issue.

**Comment by sreeder** [comment]
casing has been fixed. Closing
