### ISSUE TITLE
Unable to create new site/sampling feature

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2StreamingDataLoader#77]
I attempt to create a new site/sampling feature, however, it doesn't show up in the table. It should appear and be selected. If there is an error, then I should receive an error message. 

![image](https://cloud.githubusercontent.com/assets/5023186/25003556/31c2a320-200d-11e7-9a18-2a8969665abb.png)

**Comment by kwuz** [comment]
**ready to test on branch issue_77**

**Comment by sreeder** [comment]
this looks like it has been addressed
