### ISSUE TITLE
Database Connection breaks when strings contain ";"

### ISSUE THREAD

**Issue by kwuz** [ODM2/ODM2StreamingDataLoader#82]

**Comment by kwuz** [comment]
still needs some cleanup, will open separate issue.
Ready for testing on edit_branch

**Comment by sreeder** [comment]
@kwuz this should not be deleting the semicolon from the string. Can you see if there is a way to insert an escape character instead. If they enter a semicolon, they likely did it for a reason.

**Comment by kwuz** [comment]
sure, I'll get on that

**Comment by kwuz** [comment]
Okay, ready for testing again on branch issue_82b
